---
title: "Final Accession Options"
author: "Natalie Dietz"
date: "7/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RColorBrewer)
library(ggplot2)
library(mapdata)
library(maptools)
library(usmap)
library(raster)
```

### 2003 Options
```{r}
# Read in the coordinates from 2003 increases and display 
coord2003 <- read_csv("/Users/nataliedietz/Dropbox/oil_envr/data/codes/increases/2003/final2003options.csv")
head(coord2003)

#Create the map with state lines 
usa <- map_data("state")

#Create the map with province lines
canada <- map_data(getData(country="Canada", level="1"))
mexico <- map_data("worldHires", "Mexico")

NAmap <- ggplot() + geom_polygon(data = usa, 
                                 aes(x=long, y = lat, group = group),
                                 fill = "white", 
                                 color="black") +
    geom_polygon(data = canada, aes(x=long, y = lat, group = group), 
                 fill = "white", color="black") + 
    geom_polygon(data = mexico, aes(x=long, y = lat, group = group), 
                 fill = "white", color="black") +
    coord_fixed(xlim = c(-120, -80),  ylim = c(25, 60), ratio = 1.2)
```

```{r}
# Now, let's plot the coordinates on the map
NAmap1 <- NAmap + geom_point(data=coord2003, aes(x=coord2003$lon, y=coord2003$lat),
                            fill= "blue", color = "black", 
                            shape=21, size=3.0) 
NAmap1
```

### 2001 options
```{r}
# Read in the increases from 2001 and display 
coord2001 <- read.csv("/Users/nataliedietz/Dropbox/oil_envr/data/codes/increases/2001/final_2001_options.csv")
head(coord2001)
```

```{r}
#Plot 2001 accessions on map
NAmap2 <- NAmap + geom_point(data=coord2001, aes(x=lon, y=lat),
                            fill= "red", color = "black", 
                            shape=21, size=3.0) 
NAmap2
```

### 2000 options
```{r}
#Read in increases from 2000 and display
coord2000 <- read.csv("/Users/nataliedietz/Dropbox/oil_envr/data/codes/increases/2000/final_2000_accessions.csv")
head(coord2000)
```

```{r}
#Plot 2000 accessions on map
NAmap3 <- NAmap + geom_point(data=coord2000, aes(x=lon, y=lat),
                            fill= "purple", color = "black", 
                            shape=21, size=3.0) 
NAmap3
```

### 2002 options
```{r}
# Read in increases from 2002 and display
coord2002 <- read.csv("/Users/nataliedietz/Dropbox/oil_envr/data/codes/increases/2002/final_2002_options.csv")
head(coord2002)
```

```{r}
# Plot 2002 accessions on map
NAmap4 <- NAmap + geom_point(data=coord2002, aes(x=lon, y=lat),
                            fill= "green", color = "black", 
                            shape=21, size=3.0) 
NAmap4
```

### 2004 options
```{r}
# Read increases from 2004 and display
coord2004 <- read.csv("/Users/nataliedietz/Dropbox/oil_envr/data/codes/increases/2004/final_2004_increases.csv")
head(coord2004)
```

```{r}
# Plot 2004 accessions on mop
NAmap5 <- NAmap + geom_point(data=coord2004, aes(x=lon, y=lat),
                            fill= "pink", color = "black", 
                            shape=21, size=3.0) 
NAmap5
```

```{r}
# Read in increases from 2005 and display 
coord2005 <- read.csv("/Users/nataliedietz/Dropbox/oil_envr/data/codes/increases/2005/lat_lon2005.csv")

NAmap6 <- NAmap + geom_point(data =coord2005, aes(x=lon, y = lat), fill = "yellow", color = "black", shape=21, size = 3.0)
NAmap6
```

